# -*- coding: utf-8 -*-
"""Doimoi6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HpPeIt7TX7inzuaR4L4zDOHMBB6snO3x
"""

a,k,b,m,n=[int (i) for i in input().split()]
day=n//(a+b)
tree=day*(a+b)-a*(day//k)-b*(day//m)
temp=n-tree
while temp >= (a+b):
  day=day+ (temp//(a+b))
  tree=day*(a+b)-a*(day//k)-b*(day//m)
  temp=n-tree
while tree < n:
  day=day+1
  if day % m==0 and day % k==0: 
    tree+=0
  elif (day % m==0): 
    tree+=a
  elif (day % k==0): 
    tree+=b
  else:                 
    tree=tree+a+b
print(day)